spring:
  application:
    name: knsharding
  sharding:
    datasources:
      ds0:
        url: jdbc:mysql://localhost:3306/ds0?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
        username: root
        password: lokn
      ds1:
        url: jdbc:mysql://localhost:3306/ds1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
        username: root
        password: lokn
    tables:
      user:
        actualDataNodes: ds0.user0,ds0.user1,ds0.user2,ds1.user0,ds1.user1,ds1.user2
        databaseStrategy:
          shardingColumn: id
          algorithmExpression: ds${id % 2}
        tableStrategy:
          shardingColumn: id
          algorithmExpression: user${id % 3}